import { Injectable, NotFoundException, Logger, ForbiddenException } from '@nestjs/common';
import { InjectModel } from '@nestjs/mongoose';
import { Model, Types } from 'mongoose';
import { SosSession, SosSessionDocument, SosLocationLog, SosActivityLog } from './sos.schema';
import { SosGateway } from './sos.gateway';
import { OtpService } from '../otp/otp.service';
import { ConfigService } from '@nestjs/config';
import { Cron, CronExpression } from '@nestjs/schedule';

@Injectable()
export class SosService {
    private readonly logger = new Logger(SosService.name);

    constructor(
        @InjectModel(SosSession.name) private sosModel: Model<SosSessionDocument>,
        @InjectModel(SosLocationLog.name) private locationLogModel: Model<SosLocationLog>,
        @InjectModel(SosActivityLog.name) private activityLogModel: Model<SosActivityLog>,
        private readonly sosGateway: SosGateway,
        private readonly otpService: OtpService,
        private readonly configService: ConfigService,
    ) { }

    async startSos(userId: string, therapistId: string, therapistName: string, phone: string, location: { latitude: number; longitude: number; accuracy?: number }) {
        await this.sosModel.updateMany(
            { therapistId: new Types.ObjectId(therapistId), status: 'ACTIVE' },
            { status: 'CANCELLED' },
        );

        const session = await this.sosModel.create({
            userId: new Types.ObjectId(userId),
            therapistId: new Types.ObjectId(therapistId),
            therapistName,
            phone,
            status: 'ACTIVE',
            startLocation: location,
            lastLocation: { ...location, updatedAt: new Date() },
        });

        await this.logActivity(session._id.toString(), 'ACTIVATED', 'THERAPIST', 'Emergency SOS triggered.');
        await this.logLocation(session._id.toString(), location.latitude, location.longitude, location.accuracy);

        this.sosGateway.notifyNewSos(session);
        this.logger.error(`🚨 EMERGENCY SOS TRIGGERED: ${therapistName}`);

        return { sosSessionId: session._id.toString(), status: 'ACTIVE' };
    }

    async updateLocation(sessionId: string, location: { lat: number; lng: number; accuracy?: number; batteryLevel?: number; networkStrength?: string }) {
        const timestamp = new Date();
        const session = await this.sosModel.findByIdAndUpdate(
            sessionId,
            {
                lastLocation: {
                    latitude: location.lat,
                    longitude: location.lng,
                    accuracy: location.accuracy,
                    batteryLevel: location.batteryLevel,
                    networkStrength: location.networkStrength,
                    updatedAt: timestamp,
                },
            },
            { new: true },
        );

        if (!session) throw new NotFoundException('SOS session not found');

        await this.logLocation(sessionId, location.lat, location.lng, location.accuracy, location.batteryLevel, location.networkStrength);
        this.sosGateway.broadcastLocation(sessionId, { ...location, updatedAt: timestamp });

        return { success: true };
    }

    async generateResolutionPin(sessionId: string, adminId: string) {
        const session = await this.sosModel.findById(sessionId);
        if (!session || session.status !== 'ACTIVE') {
            throw new ForbiddenException('Cannot generate PIN for an inactive SOS session.');
        }

        const pin = Math.floor(100000 + Math.random() * 900000).toString();
        session.resolutionPin = pin;
        await session.save();

        await this.logActivity(sessionId, 'PIN_GENERATED', adminId, 'Resolution PIN generated by Admin.');
        this.sosGateway.broadcastStatusChange(sessionId, 'PIN_READY');

        return { pin };
    }

    async resolveSos(sessionId: string, pin: string, therapistId: string) {
        const session = await this.sosModel.findById(sessionId);
        if (!session) throw new NotFoundException('SOS session not found');

        if (session.resolutionPin !== pin) {
            await this.logActivity(sessionId, 'ACTIVATED', 'THERAPIST', `Incorrect PIN attempt: ${pin}`);
            throw new ForbiddenException('Invalid PIN.');
        }

        session.status = 'RESOLVED';
        session.resolvedAt = new Date();
        await session.save();

        await this.logActivity(sessionId, 'RESOLVED', 'THERAPIST', 'SOS resolved with PIN.');
        this.sosGateway.broadcastStatusChange(sessionId, 'RESOLVED');

        return { success: true, status: 'RESOLVED' };
    }

    /**
     * Phase 7: Escalation Logic
     * Manual or Auto escalation to Founder/Emergency Contacts
     */
    async escalateSos(sessionId: string, performedBy: string = 'SYSTEM') {
        const session = await this.sosModel.findById(sessionId);
        if (!session || session.status === 'RESOLVED') return;

        session.status = 'ESCALATED';
        session.escalatedAt = new Date();
        await session.save();

        await this.logActivity(sessionId, 'ESCALATED', performedBy, 'Mission Escalated: Emergency Contact Notified.');
        this.sosGateway.broadcastStatusChange(sessionId, 'ESCALATED');

        // Send SMS to Founder
        const founderMobile = this.configService.get<string>('SOS_FOUNDER_MOBILE') || '9876543210';
        const msg = `🚨 EMERGENCY ESCALATION: Therapist ${session.therapistName} (${session.phone}) has been in SOS for over 15 mins without resolution. Immediate action required. Map: https://maps.google.com/?q=${session.lastLocation.latitude},${session.lastLocation.longitude}`;

        await this.otpService.sendSms(founderMobile, msg);
        this.logger.warn(`SOS ESCALATED: ${session._id}`);
    }

    /**
     * Phase 10: Auto-Escalation Cron
     * Checks every 5 minutes for active SOS alerts older than 15 minutes
     */
    @Cron(CronExpression.EVERY_5_MINUTES)
    async handleAutoEscalation() {
        const fifteenMinsAgo = new Date(Date.now() - 15 * 60 * 1000);
        const lingeringAlerts = await this.sosModel.find({
            status: 'ACTIVE',
            createdAt: { $lt: fifteenMinsAgo }
        });

        for (const alert of lingeringAlerts) {
            await this.escalateSos(alert._id.toString(), 'SYSTEM_TIMEOUT');
        }
    }

    async logLocation(sosId: string, lat: number, lng: number, accuracy?: number, batteryLevel?: number, networkStrength?: string) {
        return this.locationLogModel.create({
            sosId: new Types.ObjectId(sosId),
            latitude: lat,
            longitude: lng,
            accuracy,
            batteryLevel,
            networkStrength
        });
    }

    async logActivity(sosId: string, eventType: string, performedBy: string, details?: string) {
        return this.activityLogModel.create({
            sosId: new Types.ObjectId(sosId),
            eventType,
            performedBy,
            details
        });
    }

    async listActive() {
        return this.sosModel.find({ status: { $in: ['ACTIVE', 'ESCALATED'] } }).sort({ createdAt: -1 }).lean().exec();
    }

    async getFullSessionData(sessionId: string) {
        const session = await this.sosModel.findById(sessionId).lean();
        if (!session) throw new NotFoundException('SOS session not found');
        const logs = await this.locationLogModel.find({ sosId: new Types.ObjectId(sessionId) }).sort({ timestamp: -1 }).limit(100).lean();
        const activities = await this.activityLogModel.find({ sosId: new Types.ObjectId(sessionId) }).sort({ timestamp: -1 }).lean();
        return { session, geoTrail: logs, activityHistory: activities };
    }

    async getMyActiveSos(userId: string) {
        return this.sosModel.findOne({ userId: new Types.ObjectId(userId), status: { $in: ['ACTIVE', 'ESCALATED'] } }).sort({ createdAt: -1 }).lean().exec();
    }
}
